### ISSUE TITLE
Bypass /usr/local/ if the user does not have permission

### ISSUE THREAD

**Issue by Root3287** [apenngrace/homebrew-vulkan#11]
I am using a work pc to build vulkan-sdk binary. I have downloaded and unzip homebrew to ```~/homebrew``` when I do ```./brew cask install vulkan-sdk``` it would download, link, but then unlink since I don't have permissions for ```/usr/local/```.

Request: Allow to install vulkan-sdk to ```~/homebrew``` when user don't have permission to ```/usr/local```

**Comment by apenngrace** [comment]
It has been about two years since I wrote this script, so I had to jog my memory a bit.  I wrote this cask script to symlink to `/usr/local` in order to avoid having to update environment variables each time a new version of the Vulkan SDK was released.  There is a [discussion here](https://github.com/Homebrew/homebrew-cask/issues/51330#) about that.

In [this post](https://vulkan.lunarg.com/issue/view/5bb7219fe46ffe07e4d318a7) over on LunarG's discussion board, they let me know the supported search paths for ICD & Layers that would avoid needing environment variables.

In [this old version of the cask script](https://github.com/apenngrace/homebrew-cask/blob/vulkan-sdk/Casks/vulkan-sdk.rb), the script did almost nothing other than download the files with brew and print a list of environment variables that you could copy and paste into your `.bash_profile`.  You could potentially use that script to create your own tap to fit your use case.

**Comment by Root3287** [comment]
Alright, I just manually download the sdk and use the provided setup-env.sh they provide.
It probably would be too complicated to hook on to a permission error and install it wherever homebrew is located instead of uninstalling itself.
