### ISSUE TITLE
Is it possible to add a pkg-config package description to the installed files?

### ISSUE THREAD

**Issue by expipiplus1** [apenngrace/homebrew-vulkan#13]
To allowing finding libvulkan.dylib with pkg-config

**Comment by apenngrace** [comment]
Would you like to submit a pull request?  I am very rusty on the use of pkg-config.  It's been a while since I've needed to use it.

This homebrew script puts symlinks for the include files and dylib files in the default search path for MacOS: `/usr/local/lib` and `/usr/local/include`.  So, the system compilers and linkers should find the files.  What would having the pkg-config file help accomplish in addition to that?

Regarding this homebrew script, most of the heavy lifting is done by the homebrew library.  Homebrew downloads the dmg file and unpacks the dmg into a folder that is named automatically based on the cask name and version.  Right now the only files that get installed are from LunarG's `dmg` image (although the script does modify a few json files to add explicit file paths).

How would a pc file be integrated into this script?  Would the homebrew script be adding an additional directory, then create a file such as  `vulkan-sdk.pc`, and then write to it?  I figure that might be cleaner than downloading a `.pc` file from Github and then modifying strings in order to specify a file path to `/usr/local/Caskroom/vulkan-sdk/{version number}/` for the various dylib and include paths for the `pkg-config` file.

**Comment by expipiplus1** [comment]
I'm afraid I don't have an OS X system to test any PR on (testing via github actions is a real pain!); this is by no means critical though!

For reference the `vulkan.pc` file I have on my linux box looks like this:

```pkgconfig
prefix=/nix/store/xz0p14g63sahdk8bfqsyk8qvahp49my3-vulkan-loader-1.2.162.0
exec_prefix=/nix/store/xz0p14g63sahdk8bfqsyk8qvahp49my3-vulkan-loader-1.2.162.0
libdir=/nix/store/xz0p14g63sahdk8bfqsyk8qvahp49my3-vulkan-loader-1.2.162.0/lib
includedir=/nix/store/n3d8q3h7qdmx2zy2yxwn8zxjx6l9rsh0-vulkan-loader-1.2.162.0-dev/include

Name: Vulkan-Loader
Description: Vulkan Loader
Version: 1.2.162
Libs: -L${libdir} -lvulkan
Libs.private:  -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc
Cflags: -I${includedir}
```

I guess that instead of the `/nix/store/` paths there would be, as you say, `/usr/local/Caskroom/...` paths. And I suppose the libs.private field would need to change.

Having this would allow build systems, such as cabal, which might specify the vulkan loader dependency via pkgconfig to work. Cabal can also specify the library name directly so it's not the end of the world, but it's a pain to have to have a separate config item for OSX and linux when this could be done by pkgconfig.

**Comment by apenngrace** [comment]
For your use case, if the libraries and include headers are installed on default compiler & linker search paths on MacOS, doesn't that make these lines from the pkg-config file redundant?

```
-L${libdir}
-I${includedir}
```

The `-lvulkan` linker option would be the same on Max & Linux, right?

You can get the current version installed by brew with `brew info vulkan-sdk`.

This script isn't anything official from LunarG, and it's not even in homebrew's official repo either... so you could also just fork it and have a repo for your own modifications too.

**Comment by expipiplus1** [comment]
> For your use case, if the libraries and include headers are installed on default compiler & linker search paths on MacOS, doesn't that make these lines from the pkg-config file redundant?
> 
> ```
> -L${libdir}
> -I${includedir}
> ```
>
> The `-lvulkan` linker option would be the same on Max & Linux, right?

Yeah, I suppose so!
 
> You can get the current version installed by brew with `brew info vulkan-sdk`.
> 
> This script isn't anything official from LunarG, and it's not even in homebrew's official repo either... so you could also just fork it and have a repo for your own modifications too.

Sure, but this seems to be the de-facto way to install on OSX and I wouldn't want to fragment things.

**Comment by apenngrace** [comment]
You could put a modified version in a private repo, or even just use your own local modified ruby script if you don’t want to fragment by having multiple versions out there.

Brew can install using a local file with ‘brew install file:///path/file.rb’.

For now, I appreciate the suggestion, but I’m trying to keep things simple and just limit the installation to files that are in LunarG’s dmg packages.

If this is the defacto script, then help me convince brew to put this back into their main repo!  It was in their repo for about six months, and then suddenly removed it... a couple years ago.

After they removed it, I put the script into my own repo just in case it is useful to someone.  I’m amazed anybody even finds this script at all!

Since I wrote it, LunarG later put a python install script within the dmg package too.  That is the official installation method from LunarG.

**Comment by expipiplus1** [comment]
> For now, I appreciate the suggestion, but I’m trying to keep things simple and just limit the installation to files that are in LunarG’s dmg packages.

Very understandable! I'd be fine if this issue were closed.

Thank you very much too for the thoughtful replies.

>  If this is the defacto script, then help me convince brew to put this back into their main repo! It was in their repo for about six months, and then suddenly removed it... a couple years ago.

happy to help, is there anything specific (and easy) I could do?
