### ISSUE TITLE
Path and 1.1.92.0 SDK

### ISSUE THREAD

**Issue by mattparks** [apenngrace/homebrew-vulkan#3]
According to LunarG https://vulkan.lunarg.com/ 1.1.92.0 has been pulled due to a defect, 1.1.92.1 will be the next version available, until then 1.1.85.0 is the latest version. I also noticed VULKAN_SDK is not being set, is that possible to do in this cask? Great work on this script!

**Comment by apenngrace** [comment]
Hi Matthew,
  Thanks for the heads up.  I’ll revert the cask back to 1.1.85.0.  

   Casks are not supposed to modify things like your .bash_profile file, but you can set VULKAN_SDK yourself if you like.  The problem with that is that you’ll have to keep changing it each time they release a new version (because file paths will change).  Rather than depending on the environment variable, this casks installation script puts symlinks to files in the standard MacOS locations (like /usr/local/bin, or /usr/local/lib).

Andrew

**Comment by apenngrace** [comment]
Hi Matthew,
  Thanks for the heads up.  I’ll revert the cask back to 1.1.85.0.  

   Casks are not supposed to modify things like your `.bash_profile` file, but you can set VULKAN_SDK yourself if you like.  The problem with that is that you’ll have to keep changing it each time they release a new version (because file paths will change).  Rather than depending on the environment variable, this cask installation script puts symlinks to files in the standard MacOS locations (like `/usr/local/bin`, or `/usr/local/lib`).

Here are the discussion threads where this got hashed out... 
- [Homebrew Discussion](https://github.com/Homebrew/homebrew-cask/issues/51330)
- [LunarG Discussion](https://vulkan.lunarg.com/issue/view/5bb7219fe46ffe07e4d318a7)

Andrew
